### ISSUE TITLE
Map in intl/lib/number_symbols_data.dart is untyped

### ISSUE THREAD

**Issue by floitschG** [dart-lang/intl#113]
_From @dskloetg on April 5, 2016 13:24_

In https://github.com/dart-lang/intl/blob/master/lib/number_symbols_data.dart

`Map numberFormatSymbols = const {`

should be `Map<String, NumberSymbols>`

_Copied from original issue: dart-lang/sdk#26192_

**Comment by alan-knight** [comment]
Interestingly, it is apparently a breaking change to put generics on this. If someone was casting it to that type already, then by adding the type it creates a fatal hint of an unnecessary cast. @leafpetersen

**Comment by dskloetg** [comment]
I added the cast in our code in order to be able to enable strong mode. But I'd be happy to have our build broken by this fix so that we can remove the cast again.

**Comment by dskloetg** [comment]
Any update on this?

**Comment by alan-knight** [comment]
Nothing so far. I've been a bit reluctant since discovering it's breaking.

**Comment by dskloetg** [comment]
It's breaking because enabling strong mode forces you to put the unnecessary cast.
Should we really allow that to cause a stalemate?
How many targets does it break?

**Comment by alan-knight** [comment]
Yes, so the strong mode "unnecessary cast" warning, and having that warning fail the build means that adding a type on a public interface is a breaking change. It probably doesn't break very many things, but we can't know how many because we don't have everyone's source code. And it has been a lower priority than lots of other things people are asking for.

**Comment by mosuem** [comment]
Closing in favor of #482 .
