### ISSUE TITLE
package:barback must be declared as a public dependency

### ISSUE THREAD

**Issue by scheglov** [dart-lang/intl#120]
The library `lib/transformer.dart` has `import 'package:barback/barback.dart';`.

This means that the package `barback` must be a public dependency, not

```
dev_dependencies:
  barback: ^0.15.2
```

This prevents Analysis Server from building linked summaries for the package `intl` and the transitive list of packages that use it.

@bwilkerson @stereotype441  @nex3

**Comment by alan-knight** [comment]
So a package with a transformer has to have barback as a runtime dependency? That doesn't seem right.

**Comment by scheglov** [comment]
Well, either this, or `lib/transformer.dart` should be removed from `lib`.
You cannot use anything from `dev_dependencies` inside of `lib`.

@kevmoo @bwilkerson @stereotype441

**Comment by alan-knight** [comment]
That seems incompatible with the instructions for transformers at https://www.dartlang.org/tools/pub/transformers

**Comment by scheglov** [comment]
@munificent 

The instructions also say:

`In your package’s pubspec.yaml file, add a dependency on the barback package:`

```
dependencies:
  barback: ^0.15.2
```

**Comment by munificent** [comment]
> So a package with a transformer has to have barback as a runtime dependency?

`dependencies` doesn't mean "runtime" dependency so much as it means "public" dependency. By putting your transformer in `lib/transformer.dart`, you're saying that other packages can use intl's transformer.

That means when an app depends on intl, it also needs to transitively get barback so that intl's transformer has access to it. That means barback needs to be in `dependencies`, not `dev_dependencies`. The latter is for dependencies that are not transitive. Generally, that means for things you only use from within `benchmark`, `example`, `test`, and `tool`.

**Comment by alan-knight** [comment]
Ah, ok.
