### ISSUE TITLE
No @@locale or _locale field found in intl_messages

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/intl#133]
I'm trying to create Czech translation of my default application messages (in English).
I'm following example here https://pub.dartlang.org/packages/intl

I translated the generated intl_messages.arb file and named it intl_messages_cs.arb (I used Google Translation Toolkit). After `generate_from_arb` I received:

    No @@locale or _locale field found in intl_messages, assuming 'messages' based on the file name.
    No @@locale or _locale field found in intl_messages_cs, assuming 'messages_cs' based on the file name.

Technically it works, when I use  `Intl.defaultLocale = 'messages_cs';` I see correct translation.

`extract_to_arb` should specify `@@locale` in arb file, as well as GTT should put this field into translated files. `extract_to_arb` should probably take the default locale of my app as a commandline parameter. Or even enforce it?

Other option is to edit arb files by hand, which doesn't seem to be sustainable ...

**Comment by alan-knight** [comment]
It seems reasonable that you could provide a locale argument and that extract_to_arb would include that, so you could use it as input to generate a fallback translation.

We can't really control what GTT generates, that's why there's the fallback mechanism to create it based on the filename. But it's not particularly smart, it just looks for the first underscore. It can't tell the difference between messages_pt_BR and intl_messages_cs. It could be smarter about that, but there are limits. Or we could at least document that better.

You can work around it by naming the file intlmessages_cs.arb, or just messages_cs.arb and it should then treat the locale as "cs".
