### ISSUE TITLE
Flutter can not use findSystemLocale()

### ISSUE THREAD

**Issue by xuexin** [dart-lang/intl#164]
compiler message: dart:html: Error: Not found: dart:html.

How can I get system language?

**Comment by zoechi** [comment]
Can you please share more code?
Seems you imported something that depends on `dart:html` which is not allowed for code run in Flutter.

**Comment by xuexin** [comment]
I import `package:intl/intl_browser.dart`, which import `dart:html`
This page shows intl support to flutter, I just try to figure out whether it can be use.
https://pub.dartlang.org/packages/intl

**Comment by xuexin** [comment]
But it's `defaultLocale` always null, `systemLocale ` always 'en_US'
How can I get system language?

**Comment by zoechi** [comment]
I saw that being asked elsewhere but I don't know if there was an answer.

**Comment by alan-knight** [comment]
There are two versions. `intl_browser.dart` is for the web.  `intl_standalone.dart` is for the VM/Flutter.  Note that the `findSystemLocale()` method there just delegates to `Platform.localeName` in dart:io.

However, I think there may be an issue there that on mobile platforms that might be giving you a Unix-style locale, e.g. the value of the environment variable, rather than making the appropriate Android/iOS calls. But I'm not sure. In Flutter, it looks like that ends up going to window.locale. I'm not sure where that comes from, but that might indicate the issue I'm remembering has been resolved.

**Comment by xuexin** [comment]
Thank you for your help.

**Comment by alan-knight** [comment]
I took a look and it does seem like Platform.localeName is working all right on Android. It seems like it has code that's trying to use the iOS locale, but it always returned en_US for me. Looks like this might be a known problem. https://github.com/flutter/flutter/issues/14128

**Comment by DmitrySikorsky** [comment]
It is possible to use conditional import like this:

`import 'package:intl/intl_standalone.dart' if (dart.library.html) 'package:intl/intl_browser.dart';`

And then just

`Intl.defaultLocale = await findSystemLocale();`

It will be possible to build on any platform without need to edit code.
