### ISSUE TITLE
Nested plural not supported by Google Translator Toolkit

### ISSUE THREAD

**Issue by KammererTob** [dart-lang/intl#188]
I might have misunderstood the documentation, but the generator does not throw any errors and my application runs as expected when i use nested plural definitions like this:

```
  String timeIsRunningOut(int seconds) => Intl.plural(seconds,
    zero: 'Time\'s up!',
    other: "Time is running out. Only ${Intl.plural(seconds,
      one: '1 second',
      other: '$seconds seconds',
      name: '_seconds',
      args: [seconds]
    )} remaining!",
    name: 'timeIsRunningOut',
    args: [seconds]);
```

The only problem is the Google Translator Toolkit. When i use it to translate my file into different languages it automatically translates the terms of the inner plural (like "seconds", "plural" and "other"), which then makes the generated .dart files (at least the affected translation) defect.
Is this a bug, or is it not allowed to nest plurals in this way?

**Comment by alan-knight** [comment]
I don't know for sure, but it might very well be a limitations of Google Translator Toolkit. Generally, it's preferred to avoid nesting because the number of possibilities that need to be translated multiplies.

If you really want to do it, you can work around it by defining two messages and then passing the result of one as a string parameter to the other.
