### ISSUE TITLE
DateFormat parsing accepts invalid dates.

### ISSUE THREAD

**Issue by simolus3** [dart-lang/intl#199]
We're using version `0.15.7` of the `intl` package. The following code:
```dart
import 'package:intl/intl.dart';

void main() {
  final DateFormat dateFormatter = DateFormat('dd.MM.yyyy');

  print(dateFormatter.parseStrict("60.01.2019"));
}
```
prints `2019-03-01 00:00:00.000`. I'd actually expect it to throw an exception in that case, as January doesn't have 60 days.  Attempting to parse `03.13.2019` (month to high) throws, as expected.

This might be related to #36

**Comment by LucasBurg** [comment]
I have the same problem. 
It seems like days are added as months.

``` 
   final v = "60/01/2019"
    try {
      final dt = DateFormat.yMd().parseStrict(v);
      print(dt.toString());
    } on FormatException catch (e) {
      print(e);
    }
```
Input => Return
60/01/2019 => 2019-03-01 00:00:00.000
32/01/2019 => 2019-02-01 00:00:00.000
33/01/2019 => 2019-02-02 00:00:00.000

**Comment by darrenaustin** [comment]
I am seeing the same problem with `0.16.1`:

```dart
try {
  final dt = DateFormat.yMd().parseStrict('1/32/2020');
  print(dt.toString());
} on FormatException catch (e) {
  print(e);
}
```
On a en_US locale yields:

2020-02-01

Which is weird because other dates such as '10/32/2020' properly throw the exception. So it isn't always adding the day overflow to the month.

We are hoping to use DateFormat.parse for a date text field validator in the new Flutter date picker, so it would be nice to get this fixed.

**Comment by alan-knight** [comment]
I think the problem is that the code is not sufficiently distinguishing the case of day of the month ('d') and day of the year ('D'). The latter is handled by treating the month as January and the day as > 31.

See the comment 
// Day of year. Setting month=January with any day of the year works

https://github.com/dart-lang/intl/blob/99cc086a6c2e72c394a54c3a6dbbae010b0d6d49/lib/src/intl/date_format_field.dart#L285

and the verify code at  
https://github.com/dart-lang/intl/blob/564be15ec616c459a30a21840ec001316e1bb9a9/lib/src/intl/date_format_helpers.dart#L133
    if (day > 31) {
      // We have an ordinal date, compute the corresponding date for the result
      // and compare to that.

I think the fix is likely that _DateBuilder needs a boolean for the type of date, or a separate field for dayOfYear rather than day. Unfortunately I can't think of a simple workaround. You could verify that the date printed with that format matches the original input, but I think that could have false positives (e.g. 02/01/2020 which might format as 2/1/2020 or vice versa)

**Comment by alan-knight** [comment]
Fix is on master - https://github.com/dart-lang/intl/commit/31c191f54d1e4966ef86f77967a9076a3bec7d04
