### ISSUE TITLE
[Russian] SHORTWEEKDAYS abbreviation correction

### ISSUE THREAD

**Issue by nvma** [dart-lang/intl#213]
Good day, thanks for an extremely convenient library. There's a small nuance: in Russian language weekdays, when abbreviated to a short form of two down-case letters, are usually ended with a dot. I.e. "вс.", "пн.", etc. 
Otherwise abbreviation gets completely blurred in a string of other words which considerably hurts UX.
Related links: [gramota.ru](http://new.gramota.ru/spravka/buro/search-answer?s=254707), [sokr.ru](http://www.sokr.ru/card/37266s58f984f6/)
```
SHORTWEEKDAYS: [
"вс",
"пн",
"вт",
"ср",
"чт",
"пт",
"сб"
],
STANDALONESHORTWEEKDAYS: [
"вс",
...
],
NARROWWEEKDAYS: [
"вс",
...
],
```
Would you be willing to consider a pull-request? Thanks for your time.

**Comment by kevmoo** [comment]
CC @alan-knight

**Comment by alan-knight** [comment]
Thanks. We get this data from CLDR, and it looks to me like the current CLDR data for this hasn't changed. but it's hard to read, so I note that ICU4J doesn't seem to use this. Possibly this is because the obvious formats that use this use the weekday in a way that already has punctuation, e.g.

ABBR_MONTH_WEEKDAY_DAY (MMMEd) =>  пн, 20 мая
YEAR_ABBR_MONTH_WEEKDAY_DAY (yMMMEd)  =>  пн, 20 мая 2019 г.

See also http://st.unicode.org/cldr-apps/v#/ru/Gregorian/

So unfortunately, if this is incorrect you need to take it up with the reference source.  http://cldr.unicode.org/index/bug-reports
