### ISSUE TITLE
DateFormat('EEE, dd MMM','pt_BR'); incorrect returned value.

### ISSUE THREAD

**Issue by srburton** [dart-lang/intl#250]
**Code**
```
final f = DateFormat('EEE, dd MMM','pt_BR');
print(f.format(DateTime.now()));
```

*Result*
`sex, 27 dez`

**expectancy**
`Sex, 27 Dez`

**Comment by deepak786** [comment]
any update?

**Comment by deepak786** [comment]
@srburton according to this article https://brazil-help.com/week.htm
The resulting output seems correct.

**Comment by emersonsiega** [comment]
I was about to open an issue related to this situation... But, searching on the web and reading about the language rules, the names of days and months must start with lowercase letters.

I think this seems weird to developers, mostly because using en_US these words starts with Uppercase letter. When we change the locale to pt_BR, we expect that these "pattern" will be maintained...

**Comment by deepak786** [comment]
@emersonsiega I agree with you.
But we have to wait to have the answer from one of the maintainers.
This issue is already very old but there was no update.

In our app, we also faced the same weird thing and I came to this thread.

**Comment by mosuem** [comment]
This is expected behavior, see the longer explanation in #388 .
