### ISSUE TITLE
NumberFormat not correct.

### ISSUE THREAD

**Issue by jaycreate** [dart-lang/intl#256]
I have set this format 

`var nf = new NumberFormat("#,###.00", "en_US");`

and put this number `nf.format(9.045);`

the correct number should be `9.05`

but function return `9.04`

however, when I put `9.0451` function return `9.05` then. 

or when I put higher amount like `102.045,`  it then it return `102.05` !
It seem some of amount correct but some are wrong.

e.g. 
15.045 => 15.04 **
16.045 => 16.05

102.045 => 102.05
207.045 => 207.04 **

**Comment by rakudrama** [comment]
This is working correctly. There are two reasons you might not get exactly the digits your are expecting.

1. [Floating point representation](https://floating-point-gui.de/). It is not possible to represent `9.045` exactly as a 64-bit floating-point number. The closest value that can be represented is 9.0449999999999999289457264239899814128875732421875. Since we are rounding not 9.045, but this other number, the right answer is `9.04`.

2. [Banker's rounding](https://en.wikipedia.org/wiki/Rounding#Round_half_to_even). Even without the approximations inherent in floating-point arithmetic, 9.045 is equidistant from 9.04 and 9.05. Both roundings are equally wrong.

**Comment by taipower** [comment]
I put the same number e.g 15.045 return 15.04 **but 16.045 return 16.05**

**Comment by jaycreate** [comment]
Hi @rakudrama, thanks for your explanation. I fully understand.

but the point is..
if those number are 64-bit .045 may come from .0499999999xxx
but when we put eg. 15.045, 16.045, 102.045 (so .045 are same) it's should return the same for .04 when rounded, but some are return .04 some return .05 this is seem not correct.

I compare with other language or Application (PHP, Excel, or Calculator Machine) 
When we put exactly .045 (not .0449999999999xx) it's always return .05

Number look not much difference but in accounting term they will not except even difference only just 0.01

Let me know if you have any advise.
Thanks.
