### ISSUE TITLE
How to deal with differences between parameters beginning with a vowel or consonant in translations?

### ISSUE THREAD

**Issue by krisztianodor** [dart-lang/intl#333]
Example:

``` dart
String dontHaveAccountQuestion(String appName) {
  return Intl.message(
    'Don\'t have a $appName account?',
    name: 'dontHaveAccountQuestion',
    args: [appName],
  );
}
```

If the appName is Asd (starts with a vowel) the result should be this in english translation:

```
Don't have an Asd account?
```

If the appName is Foo:

```
Don't have a Foo account?
```

----

I don't want to burn the appName parameter, just as a last resort. 

What's the procedure in such cases when it comes to translation?

Is there any - nice - solution? If yes, then how to deal with multiple parameters with the same problem?

**Comment by mosuem** [comment]
I think a forum such as stackoverflow is a better place for such a general question, see for example [this similar question](https://stackoverflow.com/questions/29851247/using-a-an-on-an-i18n-message). I personally do not see a good way to do this; I would probably pass the article as a separate parameter, so that the translator may or may not use it.
