### ISSUE TITLE
NumberFormat.currency doesn't work with spaces

### ISSUE THREAD

**Issue by JoueBien** [dart-lang/intl#366]
to get it to work I had to use 
```
return NumberFormat.currency(
      customPattern: '###,###.##',
    ).format(value).replaceAll(',', ' ');
```
without the replace all
`100000000.00` returns `100,000,000.00`
instead of  `100 000 000.00`

If you use spaces in the custom pattern `### ###.##` the formatter breaks and you end up with a space character at the end of the string `100000000.00 ` which prevents you from using the backspace.

en-AU, en-GB default is wrong too. It should use spaces not commas. Just like UK English, Australian English doesn't separate place values by a comma when using numbers - this includes currency. Mainly because separating a number's place values with the same character you use to sperate values in a list isn't a good idea.

The en-UK returns the USD prefixed and is still comma seperated.

**Comment by mosuem** [comment]
The separator char is specified in the `GROUP_SEP` field of the `NumberSymbols` class for each locale, which is defined as a `,` for both `en_AU`, `en_US` and `en_GB` in the [Unicode CLDR data](https://st.unicode.org/cldr-apps/v#/en/Symbols/).

This is thus expected behavior. If you want to define your own seperator, you can use custom `NumberSymbols` as explained [here](https://stackoverflow.com/questions/50133321/change-grouping-separator-in-numberformat-for-dart).
