### ISSUE TITLE
initializeDateFormatting('es_ES', null) filePath can't be null

### ISSUE THREAD

**Issue by rus0n** [dart-lang/intl#417]
i'm trying to initializaDateFormatting but the filePath can't be null, i'm using null safety. I tried with ' ' in filePath but i have this error.

> FileSystemException (FileSystemException: Cannot open file, path = 'symbols/es_ES.json' (OS Error: No such file or directory, errno = 2))

anybody can help me to fix this error? thanks

**Comment by isrishu** [comment]
code is broken suddenly. is there a fix to this????

**Comment by jamesderlin** [comment]
Also, as pointed out by https://stackoverflow.com/q/68882861/, the [`README.md`](https://github.com/dart-lang/intl/blob/master/README.md) file has an outdated example that calls `initializeDateFormatting` with a `null` `filePath`.

**Comment by jamesderlin** [comment]
The [`DateFormat` documentation](https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html) also contains multiple examples that pass `null`.

**Comment by jamesderlin** [comment]
CC @natebosch to try to get eyes on this.

**Comment by natebosch** [comment]
This package has multiple methods named `initializeDateFormatting`. If you import the one in `date_symbol_data_file.dart` then you'd hit this error. The example in the README uses `date_symbol_data_file.dart` which has an optional second argument so that looks like it could be correct.

It does look like the `DateFormat` documentation passes a `null` for all 3 examples, and likely at least 2 of those will need updates. PRs welcome.

**Comment by jamesderlin** [comment]
Ah.  You mean that the version from `date_symbol_data_local.dart` has optional parameters.  That's a bit confusing; there's no point for the `_local.dart` version to have the optional, ignored parameter when it's incompatible with the signatures from the other versions. =/
