### ISSUE TITLE
Error in For Loop when work with Date (intl)

### ISSUE THREAD

**Issue by kalias29** [dart-lang/intl#441]
In my App, I made a for loop that prints a succession of 600 consecutive dates to match a date entered by the user. here is a part of the code:
```
var date = []; // is the list that will contain all dates.
unformatted_date = Datetime.now(); //or the one entered by the user

for(var i = 1; i<600; i++){
   date.add(unformatted_date.add(Duration(days: i)));
}
```
If for example, I insert as initial date May 5, 2021, the cycle always prints me twice October 30. Even on other Dates, it happens to have two equal. It rarely happens that the Date is not there, that it is not printed

**Comment by alan-knight** [comment]
This does not appear to have any Intl code in it.

However, I suspect your issue is that a Duration(days: 1) does not really
know about calendar days, but is just the same as Duration(hours: 24). And
if you are entering a date you are probably reading it from just the date
string, so it will be created as a DateTime whose time is midnight. If you
add 24 hours to that across a Daylight Savings Time transition when the
hour goes backwards, adding 24 hours will not be enough to change the date
and you will have the same date component twice.
