### ISSUE TITLE
How to convert DateTime Era correctly 

### ISSUE THREAD

**Issue by Nut41tank** [dart-lang/intl#460]
I try to use DateFormat to convert DateTime to locale 
but I found that it need to convert ERA from AD to BC too And I'm not sure how to do so.

**Comment by natebosch** [comment]
This issue is not actionable. You should be able to print the era with `DateFormat`, but if you want a date representing some time in the BC (or BCE) era you'll need to find such a date before formatting to a String.

If this is still a problem for you please elaborate on the issue and include a minimal reproduction code sample to demonstrate.
