### ISSUE TITLE
pluralRules is wrong in english

### ISSUE THREAD

**Issue by EArminjon** [dart-lang/intl#483]
Few and many didn't work with local english (en).

After a look on the lib, i'm in trouble to understand the logic. If i well understand, intl force english locale to only have 'other' and intl quick out 'few' and 'many'. (Why ???)

Plural_rules.dart line 432
<img width="289" alt="Capture d’écran 2022-07-26 à 17 06 20" src="https://user-images.githubusercontent.com/37028599/181042139-f7d1bc79-dee7-473e-8ab2-b2fedbb98822.png">

From my arb : 
```
"test": "{count,plural, =0{None yet} =1{one} =2{two} few{{count} years (few)} many{{count} years (many)} other{{count}+ years} }",
```
```dart
Text(AppLocalizations.of(this).test);
```
Despite my few and many, other is always call for count > 2

I'm using flutter and would translate a string base on its value like 0 or 1-5 (range) or else 5+

Norme:
https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html
![Capture d’écran 2022-07-26 à 17 16 58](https://user-images.githubusercontent.com/37028599/181044625-fd808522-746f-4d46-8566-24a557df2bcb.png)

**Comment by EArminjon** [comment]
Could be interesting to handle range...

**Comment by alanknight-wk** [comment]
You included the chart that says why. The intl plural call is for cardinal numbers.

**Comment by EArminjon** [comment]
> You included the chart that says why. The intl plural call is for cardinal numbers.

Okay i see now.

Do you have an idea to help me ? I need something similar to plural to avoid making more than 10 time the 'same' (with little modification) traductions base on different numbers :/ ?

**Comment by alanknight-wk** [comment]
If your language doesn't require different translations for different numbers, then this should work fine. Like in English, it's either

-   no things
-   one thing 
-   $n things

So you only need to provide 3 cases, and you can get away with 2 if "0 things" is acceptable output.
If you're translating into a language that does more different things depending on the number (e.g. Russian) then the translation for that language will need to have more cases specified.

**Comment by EArminjon** [comment]
Our Business rule require to handle more case.

**Comment by alanknight-wk** [comment]
OK. If your business rules require you to have different text based on the number of items, and those rules don't match what Intl.plural uses, then it doesn't seem like you can use Intl.plural for that. You'd probably have to do your own division into separate messages and treat those as simple Intl.message calls. And you would need to put in extra information so that translators understand the conditions. So in pseudocode

```
if (n in 1..4) return smallNumberOfThings(n);
if (n in 5..9) return mediumNumberOfThings(n);
```
etc. where 

`String smallNumberOfThings(int n) => Intl.message('You have only $n items in your cart, you should buy more', ..., desc: 'This message is only used when n is in the range 1-4, for larger values see...');`

However, you may run into an issue that you have to additionally segment if you are translating into a language whose plural semantics don't match that. So if the language treats 1 and 2 differently than 3 and 4, then you'll need to manage that sub-segmentation yourself. You could possibly use Intl.plural for that, defining only the parts that you know are applicable, but you would have to be careful.

**Comment by EArminjon** [comment]
Okay ty for you answer :).
