### ISSUE TITLE
Wrong Date/Time Format on SK language

### ISSUE THREAD

**Issue by jozef-drabik** [dart-lang/intl#507]
Originaly brought up in [#63372](https://github.com/flutter/flutter/issues/63372) by @jans-y

I mean, this is allowed format:
2. 1. 2003
this works too:
02. 01. 2003
but this doesn't:
02.01.2003

Personally, I am not sure I have ever seen anybody in Slovakia "sk", put spaces after dots.

Double spaces or space at the end also doesn't work which is a common typo:
![image](https://user-images.githubusercontent.com/104101610/200556723-64b976bc-e782-430a-a625-225b167fe0af.png)

**Comment by mosuem** [comment]
I am not sure what the bug is - what functionality of `package:intl` are you calling? As for the date formatting in Slovakian, the source of truth is the [CLDR data](https://st.unicode.org/cldr-apps/v#/sk/Gregorian/14164b88b71705de) which specifies the format with spaces after the numbers. If you disagree, consider filing a bug with [there](https://github.com/unicode-org/cldr/blob/main/docs/requesting_changes.md). Closing for now.
