### ISSUE TITLE
Provide example project with .arb files

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/intl#84]
It would be great to have an example project showing the .arb workflow so it can be emulated easily.

There was at one point https://github.com/dart-lang/sample-polymer-intl/ but it seems to have disappeared.

**Comment by donny-dont** [comment]
Any updates here @alan-knight? I'm about done with generating ARB from our strings so wanted to see better examples of things.

**Comment by alan-knight** [comment]
OK, the sample is back. It's pretty trivial, and there's been a lot of
instability around reflectable/initialize/analyzer, but there's a version
that works (at least today, on my machine :-) at
https://github.com/alan-knight/polymer_intl

**Comment by alan-knight** [comment]
Not exactly easy to emulate, but it's also possible to look at test/message_extraction, which tests the flow. If your run debug.sh from there it will do the file generation steps and leave the results visible instead of cleaning them up after the tests run. There's a magic step in there for getting them translated, implemented by make_hardcoded_translation.dart, but otherwise it's pretty close to real.

**Comment by donny-dont** [comment]
Awesome! Thank you sir!

Any chance you can add some stuff where the string has a variable in it? From whats there it looks like the corresponding `@` value in the JSON is only required for those.

**Comment by alan-knight** [comment]
Added. Also noted that ARB is out of date, but the data files there are, um, closer. They're the map structure from ARB, without the register call.
