### ISSUE TITLE
intl can't parse 'PST' with DateFormat.

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/intl#93]
I'm attempting to parse date strings which come from Java code (specifically 'adb') and come out like this:

Fri Dec 18 14:00:38 PST 2015

I tried:
new DateFormat("EEE MMM d HH:mm:ss z y").parse(output)

But 'z' isn't the right format.  I don't see any "skeletons" for timezones at all, so resorted to explicit patterns.

I find a relevant ABBR_SPECIFIC_TZ in the test data, suggesting that this information is inside intl, just not exposed in this parse functionality.
https://github.com/dart-lang/intl/blob/1c2757633fb7a425a4ca48eb7902dbdf4960aa2c/test/date_time_format_test_data.dart#L58
?

I also could just be holding it wrong.

**Comment by alan-knight** [comment]
No, Intl doesn't know anything about time zone names. That test data is just copied from ICU output and it has some surplus formats represented that Intl can't handle.

You could hard-code "PST" into the pattern if you're just trying to get it to work right now for your own usage. If you're trying to get it to work in general, you probably shouldn't be using Intl. At least you shouldn't unless you expect adb to print these dates in a localized form. Otherwise it will fail as soon as someone tries to use it in a locale sufficiently different from en_US. And where it does work it will be much slower than a more hard-coded parsing mechanism. See https://github.com/dart-lang/intl/issues/83

**Comment by eseidelGoogle** [comment]
Yeah, I'm only using Intl because it appears to be the only package in dart to provide any date parsing. :)
http://stackoverflow.com/questions/25252675/parsing-dates-with-dart

It's a much bigger hammer than I need.  I can role my own (and already have some in the code in question):
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/device.dart#L871

So yeah, I basically have exactly #83, which means I probably want to role my own or use a different library or make a different library. :(

**Comment by mosuem** [comment]
Closing in favor of #19 .
